name: jekyll-dev-environment

services:
  jekyll:
    image: bretfisher/jekyll
    entrypoint: ["/bin/bash"]
    volumes:
      - .:/site
    stdin_open: true
    tty: true

  jekyll-serve:
    image: bretfisher/jekyll-serve
    user: root
    volumes:
      - .:/site
    ports:
      - "4000:4000"
