title: brig
tagline: devcontainers without the bloat
description: The lightweight, native Go CLI for devcontainers
author:
  name: Neil Santos
  email: nlsantos@users.noreply.github.com

remote_theme: "fongandrew/hydeout@master"
plugins:
  - jekyll-remote-theme

hydeout:
  repo: https://github.com/nlsantos/brig
